config/routes.rb
Rails.application.routes.draw do
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title,  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.all
    end
    def new
        @book = Book.new
    end
    def create
        @book = Book.new(params_book)
        if @book.save
          flash[:notice] = "book successfully created"
          redirect_to '/books'
        else
          flash[:notice] = "Something went wrong"
          render :new
        end
    end
    
    def show
      @book = Book.find_by(id: params[:id])
    end
    
    def edit
      @book = Book.find_by(id: params[:id])
    end
    
    def edit
      @book = Book.find_by(id: params[:id])
    end
    
    def update
      @book = Book.find_by(id: params[:id])
        if @book.update(params_book)
          flash[:notice] = "book successfully updated"
          redirect_to '/books'
        else
          flash[:notice] = "Something went wrong"
          render :edit
        end
    end
    def destroy
      @book = Book.find_by(id: params[:id])
      @book.destroy
      redirect_to '/books'
    end
        
    private
    def params_book
      params.require(:book).permit(:title, :price, :publishing, :author, :intro)
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>修改</h1>


<%= form_for (@book) do |form| %>
    <div>
        <%= form.label :title, '書名' %>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :price, '價格' %>
        <%= form.text_field :price %>
    </div>
    <div>
        <%= form.label :publishing, '出版社' %>
        <%= form.text_field :publishing %>
    </div>
    <div>
        <%= form.label :author, '作者' %>
        <%= form.text_field :author %>
    </div>
    <div>
        <%= form.label :intro, '簡介' %>
        <%= form.text_area :intro %>
    </div>
        <%= form.submit %>
<% end %>

app/views/books/index.html.erb
<h1>首頁</h1>

<%= link_to  "新增", new_book_path %>

<% @books.each do |book| %>
<ul>
    <li><%= link_to  "書名", book_path(book.id) %><%= book.title %></li>
    <li>價格<%= book.price %></li>
    <li>出版社<%= book.publishing %></li>
    <li>作者<%= book.author %></li>
    <li>簡介<%= book.intro %></li>
    <li><%= link_to  "修改", edit_book_path(book.id) %></li>
    <li><%= link_to  "刪除", book_path(book.id), method: 'delete', data: { confirm: 'Are you sure?' } %></li>

</ul>
<% end %>

app/views/books/new.html.erb
<h1>新增</h1>


<%= form_for (@book) do |form| %>
    <div>
        <%= form.label :title, '書名' %>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :price, '價格' %>
        <%= form.text_field :price %>
    </div>
    <div>
        <%= form.label :publishing, '出版社' %>
        <%= form.text_field :publishing %>
    </div>
    <div>
        <%= form.label :author, '作者' %>
        <%= form.text_field :author %>
    </div>
    <div>
        <%= form.label :intro, '簡介' %>
        <%= form.text_area :intro %>
    </div>
        <%= form.submit %>
<% end %>



      

app/views/books/show.html.erb
<h1><%= @book.title %><h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mystore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>